- name: Gather system facts
  ansible.builtin.setup:

- name: Add PostgreSQL GPG key
  become: yes
  ansible.builtin.shell: |
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/pgdg.gpg
  args:
    creates: /usr/share/keyrings/pgdg.gpg
  register: gpg_key_result

- name: Add PostgreSQL repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt {{ansible_distribution_release}}-pgdg main"
    state: present
    filename: pgdg
