# vars:
#   - domain:
#       name: <string>
#       fqdn: <string>
#       config_template: <string>
#       auth_basic_user: <string>
#       auth_basic_pass: <string>
#   - use_letsencrypt: <bool>

- name: Add Nginx domain configuration
  become: yes
  template:
    src: "{{ domain.config_template | mandatory }}"
    dest: /etc/nginx/sites-available/{{ domain.name | mandatory }}
    owner: www-data
    group: www-data
    mode: 0644
  notify: Restart Nginx
  tags: config

- name: Configure Let's Encrypt for the domain
  when: use_letsencrypt
  block:
    - name: Check whether a Let's Encrypt SSL certificate already exists for the domain
      become: yes
      stat:
        path: /etc/letsencrypt/live/{{ domain.fqdn | mandatory }}/cert.pem
      check_mode: no
      register: letsencrypt_certificate

    - name: Ensure Nginx is using latest config
      become: yes
      service:
        name: nginx
        state: reloaded
      when: not letsencrypt_certificate.stat.exists

    - name: Generate SSL certificate using Certbot
      become: yes
      command: "certbot certonly --webroot --email {{ letsencrypt_service_admin_email | mandatory }} --agree-tos --webroot-path={{ letsencrypt_webroot_directory | mandatory }} -d {{ domain.fqdn | mandatory }} --non-interactive"
      when: not letsencrypt_certificate.stat.exists
      notify: Restart Nginx

- name: Set up basic auth
  when: domain.auth_basic_user != ''
  become: yes
  htpasswd:
    path: /etc/nginx/passwords/{{ domain.name }}
    name: "{{ domain.auth_basic_user }}"
    password: "{{ domain.auth_basic_pass }}"
  notify: Restart Nginx

- name: Enable Nginx domain configuration
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ domain.name | mandatory }}
    dest: /etc/nginx/sites-enabled/{{ domain.name | mandatory }}
    owner: www-data
    group: www-data
    state: link
  notify: Restart Nginx
  tags: config
