- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted
  tags: always

- name: Restart PHP FPM
  become: yes
  service:
    name: php8.0-fpm
    state: restarted
  tags: always

- name: Restart Zabbix Server
  become: yes
  service:
    name: zabbix-server
    state: restarted
  tags: always
