- name: Download Zabbix Package
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb

- name: Add ppa Repository
  apt_repository: repo=ppa:ondrej/php
    
- name: Update APT packages
  apt:
    upgrade: "yes"
    update_cache: yes

- name: Install Zabbix Server & Frontend
  apt:
    pkg:
    - zabbix-server-pgsql 
    - zabbix-frontend-php 
    - php8.0-pgsql 
    - zabbix-nginx-conf
    - zabbix-agent

- name: Migrate Database
  shell: zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix

- name: Configure PHP FPM
  become: yes
  template:
    src: php-fpm.conf.j2
    dest: /etc/zabbix/php-fpm.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart PHP FPM
  tags: config

- name: Configure Zabbix Server
  become: yes
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart Zabbix Server
  tags: config

- name: Configure Zabbix Frontend
  become: yes
  template:
    src: zabbix.conf.php.j2
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    owner: www-data
    group: www-data
    mode: 0600
  tags: config