- name: Install Isolate prerequisite packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential # Required to build some CMS Python dependencies
    - cgroup-lite
    - libcap-dev
  tags: packages

- name: Ensure Isolate repo directory exists
  become: yes
  file:
    path: /opt/isolate
    owner: "{{ ansible_user }}"
    mode: '0755'
    state: directory

- name: Check out the Isolate repository
  git:
    repo: "{{ isolate_repo }}"
    version: "{{ isolate_version }}"
    dest: /opt/isolate
    accept_hostkey: yes
    depth: 1

- name: Build Isolate
  make:
    chdir: /opt/isolate
    target: isolate

- name: Ensure Isolate parent directories exist
  become: yes
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  with_items:
    - /var/local/lib
    - /usr/local/bin
    - /usr/local/etc

- name: Ensure Isolate box root directory exists
  become: yes
  file:
    path: /var/local/lib/isolate
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Install Isolate binary
  become: yes
  copy:
    src: /opt/isolate/isolate
    dest: /usr/local/bin/isolate
    remote_src: yes
    owner: root
    group: "{{ isolate_group }}"
    mode: '04750' # setuid bit on, only owner and group can execute

- name: Copy Isolate config
  become: yes
  template:
    src: isolate.j2
    dest: /usr/local/etc/isolate
    owner: root
    group: "{{ isolate_group }}"
    mode: '0644'
  tags: config

- name: Apply Isolate optimizations
  import_tasks: apply_optimizations.yml
