# vars:
#   gitlab_fqdn: <string>
#   gitlab_runner_registration_token: <string>

- name: Download GitLab runner packages
  become: yes
  shell: curl -sS https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | bash

- name: Install GitLab runner
  become: yes
  package:
    name: gitlab-runner
    state: present
  environment:
    GITLAB_RUNNER_DISABLE_SKEL: "true"

- name: Register GitLab runner
  become: yes
  command: |
    gitlab-runner register \
    --non-interactive \
    --url "https://{{ gitlab_fqdn }}" \
    --registration-token "{{ gitlab_runner_registration_token }}" \
    --executor shell
